# Используем официальный образ Python 3.12
FROM python:3.12-slim

# Устанавливаем системные зависимости
RUN apt-get update && apt-get install -y git

# Устанавливаем Python-библиотеки
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы проекта
COPY . /app

# Запускаем Streamlit
EXPOSE 8501
CMD ["streamlit", "run", "app_bert.py", "--server.port=8501", "--server.address=0.0.0.0"]
